name: Publish Notebooks

on:
  push:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"
    - name: Merge main -> publish
      run: |
        git fetch
        git checkout publish
        git config user.name "Github Actions Bot"
        git config user.email ""
        git merge main
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        poetry config virtualenvs.create false
        poetry install
    - name: Convert py scripts to notebooks and execute
      run: chmod u+x .github/workflows/build_notebooks.sh && .github/workflows/build_notebooks.sh
    - name: Publish notebooks to html
      run: |
        mkdir -p docs
        jupyter nbconvert --to html --template classic --output-dir='./docs' outputs/*.ipynb
    - name: Publish
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Build and publish notebooks ${{ steps.date.outputs.date }}
        branch: publish
        file_pattern: docs/* outputs/*
        add_options: '-f'
