name: Publish Notebooks

on:
  push:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Merge main -> publish
      run: |
        git fetch
        git checkout publish
        git merge main
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        poetry install
    - name: Convert .py scripts to notebooks and execute
      run: |
        jupytext --to notebook --outdir outputs notebooks/chapter_16.py
    - name: Publish notebooks to html
      run: |
        jupyter nbconvert --to html --outdir docs outputs/chapter_16.ipynb
